#!/bin/sh
#
# @name Phoenix SITL for SIH
#
# @type Plane
#
# @maintainer Romain Chiappinelli <romain.chiap@gmail.com>

. ${R}etc/init.d/rc.fw_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=sihsim}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=airplane}

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

param set-default SIH_T_MAX 276  # thrust in Newtons? P5 combined thrust of 2 engines
param set-default SIH_MASS 19  # mass in kilograms of P5 (approx 42 lbs)
param set-default SIH_IXX 7.3
param set-default SIH_IYY 5.34
param set-default SIH_IZZ 10.4
param set-default SIH_IXZ 0.0
param set-default SIH_KDV 2.2  # this was 0.2.  It should probably be higher for a larger plane.

param set-default SIH_VEHICLE_TYPE 6 	# sih as phoenix plane
param set-default RWTO_TKOFF 1  # enable takeoff from runway (as opposed to launched)

param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.3

# SIH for now hardcodes this configuration which we need to match in the airframe files.
# param set-default CA_SV_CS_COUNT 3
# param set-default CA_SV_CS0_TRQ_R 1
# param set-default CA_SV_CS0_TYPE 15  # single channel aileron
# param set-default CA_SV_CS1_TRQ_P 1
# param set-default CA_SV_CS1_TYPE 3  # elevator
# param set-default CA_SV_CS2_TRQ_Y 1
# param set-default CA_SV_CS2_TYPE 4  # rudder

# use dual ailerons instead of a single channel aileron
param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS2_TRQ_P 1
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS3_TRQ_Y 1
param set-default CA_SV_CS3_TYPE 4

param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202
param set-default PWM_MAIN_FUNC3 203
param set-default PWM_MAIN_FUNC4 204
param set-default PWM_MAIN_FUNC5 101

param set-default EKF2_GPS_DELAY 0

# Rate controllers
param set-default FW_RR_P 0.0501
param set-default FW_RR_I 2.0000
param set-default FW_RR_D 0.0000
param set-default FW_RR_FF 0.0000
param set-default FW_RR_IMAX 1.0000

param set-default FW_PR_P 0.0800
param set-default FW_PR_I 2.5000
param set-default FW_PR_D 0.0000
param set-default FW_PR_FF 0.0000
param set-default FW_PR_IMAX 1.0000

param set-default FW_YR_P 0.0500
param set-default FW_YR_I 3.0000
param set-default FW_YR_D 0.0000
param set-default FW_YR_FF 0.0000
param set-default FW_YR_IMAX 1.0000

# gripper stuff
param set-default SIH_HAS_GRIPPER 1
param set-default SIH_PAYLOAD_MASS 6.35  # 14 lbs in kg

param set-default NAV_LOITER_RAD 150 # big loiter radius for a big plane
param set-default RTL_LOITER_RAD 150

param set-default FW_AIRSPD_MAX 44.7  # 100 mph in m/s
param set-default FW_AIRSPD_MIN 17.8  # 40 mph in m/s
param set-default FW_AIRSPD_TRIM 24.58  # 55 mph in m/s
param set-default FW_AIRSPD_STALL 16.09  # 36 mph in m/s
